export const GOOD_FAVES = [
  "RoboCop",
  "Koyaanisqatsi",
  "The Life Aquatic with Steve Zissou",
  "The Blues Brothers",
  "An American Werewolf in London",
  "Assault on Precinct 13",
  "Das Boot",
  "Madonna: Truth or Dare",
  "Full Metal Jacket",
  "Total Recall",
  "Contact",
  "Basic Instinct",
  "The Taking of Pelham One Two Three",
  "Chungking Express",
  "Terminator 2: Judgment Day",
  "Trading Places",
  "Clueless",
  "Children of Men",
  "Alien",
  "Lost in Translation",
  "2001: A Space Odyssey",
  "Fight Club",
  "A Clockwork Orange",
  "E.T. the Extra-Terrestrial",
  "The Devil Wears Prada",
  "After Hours",
  "Nineteen Eighty-Four",
  "Am\u00e9lie",
  "Blade Runner",
  "Die Hard",
  "The Adventures of Buckaroo Banzai Across the 8th Dimension",
  "Her",
  "Catch Me If You Can",
  "L\u00e9on: The Professional",
  "Mon Oncle",
  "Mission: Impossible \u2013 Fallout",
  "Eastern Promises",
  "Jurassic Park",
  "Bridesmaids",
  "Predator",
  "Election",
  "The Fifth Element",
  "In the Line of Fire",
  "Time Bandits",
  "Animal Crackers",
  "Romy and Michele's High School Reunion",
  "Working Girl",
  "L.A. Confidential",
  "Nikita",
  "Demolition Man",
  "L.A. Story",
  "Falling Down",
  "London",
  "The Rock",
  "Tangerine",
  "Class of 1999",
  "Airplane!",
  "Little Shop of Horrors",
  "Step Brothers",
  "Thor: Ragnarok",
  "Due Date",
  "Gravity",
  "Shame",
  "Gattaca",
  "The Town",
  "The Accountant",
  "The Bourne Identity",
  "The Abyss",
  "The Silence of the Lambs",
  "Indiana Jones and the Last Crusade",
  "Jack Reacher",
  "Police Academy",
  "Gremlins 2: The New Batch",
  "Beverly Hills Cop",
  "Crank: High Voltage",
  "Drive",
  "Black Rain",
  "The Libertine",
  "A View to a Kill",
  "Superman III",
  "Dirty Rotten Scoundrels",
];

export function shuffleNine(titles: readonly string[]) {
  const pool = titles.filter((title) => title.toLowerCase() !== "robocop");
  const buf = new Uint32Array(1);
  for (let i = pool.length - 1; i > 0; i -= 1) {
    crypto.getRandomValues(buf);
    const j = buf[0]! % (i + 1);
    const swap = pool[i]!;
    pool[i] = pool[j]!;
    pool[j] = swap;
  }
  return ["RoboCop", ...pool.slice(0, 9)];
}

