/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as NearRouteImport } from './routes/near'
import { Route as ApiPanoRouteImport } from './routes/api/pano'
import { Route as ApiTileRouteImport } from './routes/api/tile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const NearRoute = NearRouteImport.update({
  id: '/near',
  path: '/near',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPanoRoute = ApiPanoRouteImport.update({
  id: '/api/pano',
  path: '/api/pano',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTileRoute = ApiTileRouteImport.update({
  id: '/api/tile',
  path: '/api/tile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/locations': typeof LocationsRoute
  '/near': typeof NearRoute
  '/api/pano': typeof ApiPanoRoute
  '/api/tile': typeof ApiTileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/locations': typeof LocationsRoute
  '/near': typeof NearRoute
  '/api/pano': typeof ApiPanoRoute
  '/api/tile': typeof ApiTileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/locations': typeof LocationsRoute
  '/near': typeof NearRoute
  '/api/pano': typeof ApiPanoRoute
  '/api/tile': typeof ApiTileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/locations' | '/near' | '/api/pano' | '/api/tile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/locations' | '/near' | '/api/pano' | '/api/tile'
  id: '__root__' | '/' | '/locations' | '/near' | '/api/pano' | '/api/tile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocationsRoute: typeof LocationsRoute
  NearRoute: typeof NearRoute
  ApiPanoRoute: typeof ApiPanoRoute
  ApiTileRoute: typeof ApiTileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/near': {
      id: '/near'
      path: '/near'
      fullPath: '/near'
      preLoaderRoute: typeof NearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pano': {
      id: '/api/pano'
      path: '/api/pano'
      fullPath: '/api/pano'
      preLoaderRoute: typeof ApiPanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tile': {
      id: '/api/tile'
      path: '/api/tile'
      fullPath: '/api/tile'
      preLoaderRoute: typeof ApiTileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocationsRoute: LocationsRoute,
  NearRoute: NearRoute,
  ApiPanoRoute: ApiPanoRoute,
  ApiTileRoute: ApiTileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
